resolver: lts-7.8
compiler: ghcjs-0.2.1.9007008_ghc-8.0.1
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9007008_ghc-8.0.1:
          url: http://ghcjs.tolysz.org/ghc-8.0-2016-11-07-lts-7.8-9007008.tar.gz
          sha1: 190300a3725cde44b2a08be9ef829f2077bf8825

packages:
- '.'
- '../common'
- location:
    git: git@github.com:ghcjs/ghcjs-ffiqq.git
    commit: b52338c2dcd3b0707bc8aff2e171411614d4aedb

# for testing
- location:
    git: git@github.com:plow-technologies/ghcjs-jsval-combinators.git
    commit: 46e481dd5b762c785cb5e62b956a19e1e62488f4
  extra-dep: true
- location:
    git: git@github.com:plow-technologies/ghcjs-hspec-json.git
    commit: a8452b13252411db2f46c803258eee719646aea6
  extra-dep: true
extra-deps:
- reflex-dom-0.3
- reflex-0.4.0 
- ghcjs-dom-0.2.4.0
- ref-tf-0.4.0.1
